# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
            ],
        ),
    ]
