# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filess',
            fields=[
                ('f_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('c_date', models.CharField(max_length=255)),
                ('c_time', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
    ]
