# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-03-24 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230324_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filess',
            new_name='Files',
        ),
    ]
